# Generated by Django 3.2.9 on 2023-06-13 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(db_index=True, max_length=255, verbose_name='field')),
                ('value', models.BinaryField(verbose_name='value')),
                ('fmodel', models.CharField(max_length=255, verbose_name='field type')),
                ('date_begin', models.DateTimeField(editable=False, verbose_name='begin')),
                ('date_end', models.DateTimeField(auto_now_add=True, verbose_name='end')),
                ('user', models.CharField(blank=True, default='anonymous~root', max_length=255, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'change log',
                'verbose_name_plural': 'changes logs',
                'ordering': ['-date_end'],
                'abstract': False,
            },
        ),
    ]
