# Generated by Django 3.2.9 on 2023-06-13 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelChangeLog',
        ),
    ]
