from django.utils.translation import gettext_lazy as _

PREPARATION = "PREPARATION"
READY = "READY"
WAITING = "WAITING"
REFUSED = "REFUSED"
CANCELLED = "CANCELLED"
SIGNED = "SIGNED"
ERROR = "ERROR"

PREPARATION_TR = _("En préparation")
READY_TR = _("Prêt")
WAITING_TR = _("En attente")
REFUSED_TR = _("Refusé")
CANCELLED_TR = _("Annulé")
SIGNED_TR = _("Signé")
ERROR_TR = _("En erreur")

STATUS_TRANSACTION = (
    (PREPARATION, PREPARATION_TR),
    (READY, READY_TR),
    (WAITING, WAITING_TR),
    (SIGNED, SIGNED_TR),
    (REFUSED, REFUSED_TR),
    (CANCELLED, CANCELLED_TR),
    (ERROR, ERROR_TR),
)

STATUS_DOCUMENT = (
    (PREPARATION, PREPARATION_TR),
    (WAITING, WAITING_TR),
    (SIGNED, SIGNED_TR),
    (REFUSED, REFUSED_TR),
    (CANCELLED, CANCELLED_TR),
    (ERROR, ERROR_TR),
)

STATUS_SIGNATORY = (
    (PREPARATION, PREPARATION_TR),
    (WAITING, WAITING_TR),
    (SIGNED, SIGNED_TR),
    (REFUSED, REFUSED_TR),
    (CANCELLED, CANCELLED_TR),
    (ERROR, ERROR_TR),
)

OBSERVER = "OBSERVER"
VALIDATOR = "VALIDATOR"
SIGNATORY = "SIGNATORY"
OBSERVER_TR = _("Observateur")
VALIDATOR_TR = _("Validateur")
SIGNATORY_TR = _("Signataire")

ROLE_SIGNATORY = (
    (OBSERVER, OBSERVER_TR),
    (VALIDATOR, VALIDATOR_TR),
    (SIGNATORY, SIGNATORY_TR),
)

EMAIL = "BY_EMAIL"
SMS = "BY_SMS"
EMAIL_TR = _("Code envoyé par email")
SMS_TR = _("Code envoyé par sms")
MODE_SIGNATORY = (
    (EMAIL, EMAIL_TR),
    (SMS, SMS_TR),
)