# Generated by Django 3.0.6 on 2020-05-29 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mighty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('code', models.PositiveSmallIntegerField(choices=[(60, 'EMERGENCY'), (55, 'ALERT'), (50, 'CRITICAL'), (40, 'ERROR'), (30, 'WARNING'), (25, 'NOTICE'), (20, 'INFO'), (10, 'DEBUG')], default=10, editable=False)),
                ('message', models.TextField(editable=False)),
                ('user', models.CharField(max_length=255)),
            ],
        ),
    ]
