# Generated by Django 3.0.6 on 2020-05-06 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mighty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internetprotocol',
            name='date_create',
        ),
        migrations.RemoveField(
            model_name='internetprotocol',
            name='date_update',
        ),
        migrations.RemoveField(
            model_name='internetprotocol',
            name='is_disable',
        ),
        migrations.RemoveField(
            model_name='internetprotocol',
            name='logfields',
        ),
        migrations.RemoveField(
            model_name='internetprotocol',
            name='search',
        ),
        migrations.RemoveField(
            model_name='internetprotocol',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='internetprotocol',
            name='update_by',
        ),
        migrations.RemoveField(
            model_name='useragent',
            name='date_create',
        ),
        migrations.RemoveField(
            model_name='useragent',
            name='date_update',
        ),
        migrations.RemoveField(
            model_name='useragent',
            name='is_disable',
        ),
        migrations.RemoveField(
            model_name='useragent',
            name='logfields',
        ),
        migrations.RemoveField(
            model_name='useragent',
            name='search',
        ),
        migrations.RemoveField(
            model_name='useragent',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='useragent',
            name='update_by',
        ),
    ]
