# Generated by Django 3.0.7 on 2020-06-09 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mighty', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.RenameField(
            model_name='loguser',
            old_name='user',
            new_name='model_id',
        ),
    ]
