# Generated by Django 3.0.6 on 2020-06-06 11:33

import django.contrib.sessions.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('mighty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxySession',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sessions.session',),
            managers=[
                ('objects', django.contrib.sessions.models.SessionManager()),
            ],
        ),
    ]
