# Generated by Django 3.0.6 on 2020-05-07 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mighty.applications.twofactor.models
import mighty.models
import mighty.models.base
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mighty', '0002_auto_20200506_1351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nationality',
            options={'default_permissions': ('add', 'detail', 'list', 'change', 'delete', 'disable', 'enable', 'export', 'import'), 'ordering': ['country'], 'verbose_name': 'nationality', 'verbose_name_plural': 'nationalities'},
        ),
        migrations.AlterField(
            model_name='nationality',
            name='alpha2',
            field=models.CharField(max_length=2, verbose_name='alpha2'),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='country',
            field=models.CharField(max_length=255, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='numeric',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='numeric'),
        ),
        migrations.CreateModel(
            name='Twofactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('logfields', mighty.models.JSONField(blank=True, default=mighty.models.base.default_logfield_dict, null=True)),
                ('is_disable', models.BooleanField(default=False, editable=False, verbose_name='Is disable')),
                ('search', models.TextField(blank=True, db_index=True, null=True)),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('update_by', models.CharField(blank=True, editable=False, max_length=254, null=True, verbose_name='Updated by')),
                ('code', models.PositiveIntegerField(db_index=True, default=mighty.applications.twofactor.models.generate_code)),
                ('is_consumed', models.BooleanField(default=False)),
                ('mode', models.CharField(choices=[('EMAIL', 'email'), ('SMS', 'sms')], max_length=255)),
                ('status', models.CharField(choices=[('PREPARE', 'prepare'), ('SENT', 'sent'), ('RECEIVED', 'received'), ('ERROR', 'error')], default='PREPARE', editable=False, help_text='<a href="check"></a>', max_length=100)),
                ('backend', models.CharField(editable=False, max_length=255)),
                ('response', models.TextField(editable=False)),
                ('subject', models.CharField(max_length=255)),
                ('html', models.TextField()),
                ('txt', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_create'],
                'permissions': [('can_check', 'Check status')],
                'abstract': False,
                'default_permissions': ('add', 'detail', 'list', 'change', 'delete', 'disable', 'enable', 'export', 'import'),
            },
        ),
    ]
