# Generated by Django 3.0.2 on 2020-01-25 13:13

from django.db import migrations, models
import mighty.functions


class Migration(migrations.Migration):

    dependencies = [
        ('mighty', '0002_user_nationalities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nationality',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=mighty.functions.image_directory_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=mighty.functions.image_directory_path),
        ),
    ]
