# Generated by Django 3.0.6 on 2020-06-06 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mighty', '0003_session'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProxySession',
        ),
    ]
