# Generated by Django 3.0.2 on 2020-04-08 03:11

from django.db import migrations
import mighty.models
import mighty.models.alert


class Migration(migrations.Migration):

    dependencies = [
        ('mighty', '0003_auto_20200125_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='errors',
        ),
        migrations.AlterField(
            model_name='user',
            name='alerts',
            field=mighty.models.JSONField(blank=True, default=mighty.models.alert.default_alert_dict, null=True),
        ),
    ]
