# Generated by Django 3.0.7 on 2020-06-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mighty', '0003_auto_20200609_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='asctime',
        ),
        migrations.RemoveField(
            model_name='log',
            name='levelname',
        ),
        migrations.RemoveField(
            model_name='log',
            name='message',
        ),
        migrations.RemoveField(
            model_name='log',
            name='threadNa',
        ),
        migrations.AlterField(
            model_name='log',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time when the LogRecord was created (as returned by time.time()).'),
        ),
        migrations.AlterField(
            model_name='log',
            name='stack_info',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Stack frame information (where available) from the bottom of the stack in the current thread, up to and including the stack frame of the logging call which resulted in the creation of this record.'),
        ),
    ]
