# Generated by Django 3.0.6 on 2020-06-06 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mighty', '0004_delete_proxysession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={},
        ),
        migrations.AlterModelTable(
            name='session',
            table='django_sessions',
        ),
    ]
