# Generated by Django 3.0.5 on 2020-04-22 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('mighty', '0004_auto_20200408_0311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ipv4',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ipv6',
        ),
        migrations.AddField(
            model_name='user',
            name='method_backend',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Creation method'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, max_length=20, null=True, unique=True, verbose_name='Phone'),
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('update_by', models.CharField(blank=True, editable=False, max_length=254, null=True, verbose_name='Updated by')),
                ('is_disable', models.BooleanField(default=False, editable=False, verbose_name='Is disable')),
                ('Phone', phone_field.models.PhoneField(blank=True, max_length=31, null=True, unique=True, verbose_name='Phone')),
                ('default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_phone', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'default_permissions': ('add', 'detail', 'list', 'change', 'delete', 'export', 'import', 'disable', 'enable'),
            },
        ),
        migrations.CreateModel(
            name='InternetProtocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('update_by', models.CharField(blank=True, editable=False, max_length=254, null=True, verbose_name='Updated by')),
                ('is_disable', models.BooleanField(default=False, editable=False, verbose_name='Is disable')),
                ('ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ip', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'default_permissions': ('add', 'detail', 'list', 'change', 'delete', 'export', 'import', 'disable', 'enable'),
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('update_by', models.CharField(blank=True, editable=False, max_length=254, null=True, verbose_name='Updated by')),
                ('is_disable', models.BooleanField(default=False, editable=False, verbose_name='Is disable')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_email', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'default_permissions': ('add', 'detail', 'list', 'change', 'delete', 'export', 'import', 'disable', 'enable'),
            },
        ),
    ]
