# Generated by Django 3.0.6 on 2020-05-27 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mighty.models
import mighty.models.base
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mighty', '0005_graphic_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('logfields', mighty.models.JSONField(blank=True, default=mighty.models.base.default_logfield_dict, null=True)),
                ('is_disable', models.BooleanField(default=False, editable=False, verbose_name='Is disable')),
                ('search', models.TextField(blank=True, db_index=True, null=True)),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('update_by', models.CharField(blank=True, editable=False, max_length=254, null=True, verbose_name='Updated by')),
                ('default', models.BooleanField(default=False)),
                ('street_number', models.PositiveIntegerField(verbose_name='street number')),
                ('way', models.CharField(blank=True, choices=[('ALL', 'Allée'), ('AV', 'Avenue'), ('BD', 'Boulevard'), ('CAR', 'Carrefour'), ('CHS', 'Chaussée'), ('CHE', 'Chemin'), ('CITE', 'Cité'), ('COR', 'Corniche'), ('CRS', 'Cours'), ('DSC', 'Descente'), ('DOM', 'Domaine'), ('ECA', 'Ecart'), ('ESP', 'Esplanade'), ('FG', 'Faubourg'), ('GR', 'Grande Rue'), ('HLE', 'Halle'), ('HAM', 'Hameau'), ('IMP', 'Impasse'), ('LD', 'Lieu-dit'), ('LOT', 'Lotissement'), ('MAR', 'Marché'), ('MTE', 'Montée'), ('PRV', 'Parvis'), ('PAS', 'Passage'), ('PL', 'Place'), ('PLN', 'Plaine'), ('PLT', 'Plateau'), ('PRO', 'Promenade'), ('QUAI', 'Quai'), ('QUA', 'Quartier'), ('ROC', 'Rocade'), ('RPT', 'Rond-point'), ('RTE', 'Route'), ('RUE', 'Rue'), ('RLE', 'Ruelle'), ('RES', 'Résidence'), ('SEN', 'Sente - Sentier'), ('SQ', 'Square'), ('TPL', 'Terre-plein'), ('TRA', 'Traverse'), ('VLA', 'Villa'), ('VLGE', 'Village')], max_length=4, null=True, verbose_name='way')),
                ('route', models.CharField(blank=True, max_length=255, null=True, verbose_name='route')),
                ('locality', models.CharField(blank=True, max_length=255, null=True, verbose_name='locality')),
                ('postal_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='postal code')),
                ('state', models.CharField(blank=True, max_length=255, null=True, verbose_name='state')),
                ('state_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='state code')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='country')),
                ('country_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='country code')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'abstract': False,
            },
        ),
    ]
