# Generated by Django 3.0.6 on 2020-06-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mighty', '0005_auto_20200606_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='channel',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
