# Generated by Django 3.0.5 on 2020-04-22 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mighty', '0006_auto_20200422_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='Phone',
            new_name='phone',
        ),
    ]
