# Generated by Django 3.0.6 on 2020-05-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mighty', '0006_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='cedex',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='cedex'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='cedex_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='cedex code'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='complement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='index',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='special',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
