# Generated by Django 3.0.6 on 2020-05-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mighty', '0007_auto_20200527_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='street_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='street number'),
        ),
    ]
